all: examples mat_vec_arith block_operations final_ornek eigen_array \
	gelismis_tanimlama aliasing

examples: examples.cpp
	g++ -std=c++17 examples.cpp -o examples.exe

mat_vec_arith: mat_vec_arith.cpp
	g++ -std=c++17 mat_vec_arith.cpp -o mat_vec_arith.exe

block_operations: block_operations.cpp
	g++ -std=c++17 block_operations.cpp -o block_operations.exe

final_ornek: final_ornek.cpp
	g++ -std=c++17 final_ornek.cpp -o final_ornek.exe

eigen_array: eigen_array.cpp
	g++ -std=c++17 eigen_array.cpp -o eigen_array.exe

gelismis_tanimlama: gelismis_tanimlama.cpp
	g++ -std=c++17 gelismis_tanimlama.cpp -o gelismis_tanimlama.exe

aliasing: aliasing.cpp
	g++ -std=c++17 aliasing.cpp -o aliasing.exe
